
services:
  service-a:
    build: ./shorter-service
    container_name: shorter-service
    ports:
      - "${SERVICE_PORT}:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:7
    container_name: redisdb
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:15
    container_name: psqldb
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DB}
    ports:
      - "${PSQL_PORT}:5432"

volumes:
  redis-data:
